version: '3.8'

services:
  permissions-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SQL_SERVER_CONNECTION_STRING=Persist Security Info=False;Encrypt=false;User ID=sa;Password=Dell1#admin;Initial Catalog=PermissionsDB;Server=sqlsvr-dev
    depends_on:
      - kafka
      - elasticsearch
      - sql-server

  kafka:
    image: wurstmeister/kafka:2.12-2.8.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "permissions:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  sqlserver:
    container_name: sqlsvr-dev
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "5432:5432"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Dell1#admin
      MSSQL_PID: Developer
